#!/bin/bash
# ============================================================================
# NeverEndingQuest-TTRPG - macOS Git Installer
# Usage (after download): /bin/bash install_neverendingquest_macos.sh
# ============================================================================

set -u

REPO_OWNER="zeug-zz"
REPO_NAME="NeverEndingQuest-TTRPG"
REPO_BRANCH="main"
REPO_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}.git"

INSTALL_DIR="${HOME}/${REPO_NAME}"
APP_NAME="NeverEndingQuest Server.app"
APP_PATH="/Applications/${APP_NAME}"

TMP_DIR="$(mktemp -d "/tmp/neq-macos-installer.XXXXXX")"
APPLESCRIPT_PATH="${TMP_DIR}/start_neverendingquest_server.applescript"
TMP_APP_PATH="${TMP_DIR}/${APP_NAME}"
ICONSET_DIR="${TMP_DIR}/neq_icon.iconset"
ICON_ICNS_PATH="${TMP_DIR}/neq_icon.icns"

cleanup() {
    rm -rf "${TMP_DIR}"
}
trap cleanup EXIT

print_header() {
    printf "\n========================================\n"
    printf "  NeverEndingQuest-TTRPG Installation\n"
    printf "========================================\n\n"
}

print_step() {
    printf "\n%s\n" "$1"
}

fail() {
    printf "[ERROR] %s\n" "$1"
    exit 1
}

warn() {
    printf "[WARNING] %s\n" "$1"
}

ok() {
    printf "[OK] %s\n" "$1"
}

require_command() {
    local cmd="$1"
    local install_hint="$2"

    if ! command -v "${cmd}" >/dev/null 2>&1; then
        fail "${cmd} not found. ${install_hint}"
    fi
}

check_python_version() {
    local py_cmd="$1"
    "${py_cmd}" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 9) else 1)' || return 1
    return 0
}

install_or_update_repo() {
    if [ -d "${INSTALL_DIR}/.git" ]; then
        ok "Existing Git install detected at ${INSTALL_DIR}"

        if [ -n "$(git -C "${INSTALL_DIR}" status --porcelain)" ]; then
            warn "Local changes detected. Skipping git pull to avoid overwriting files."
            warn "You can update later with: cd \"${INSTALL_DIR}\" && git pull --ff-only origin ${REPO_BRANCH}"
            return 0
        fi

        print_step "Updating existing installation..."
        git -C "${INSTALL_DIR}" fetch origin "${REPO_BRANCH}" || warn "Fetch failed. Continuing with local version."
        git -C "${INSTALL_DIR}" pull --ff-only origin "${REPO_BRANCH}" || fail "Git pull failed. Run manually in ${INSTALL_DIR}."
        ok "Repository updated"
        return 0
    fi

    if [ -d "${INSTALL_DIR}" ]; then
        local backup_dir
        backup_dir="${INSTALL_DIR}-backup-$(date +%Y%m%d-%H%M%S)"
        warn "Non-git directory exists at install location."
        warn "Moving existing folder to: ${backup_dir}"
        mv "${INSTALL_DIR}" "${backup_dir}" || fail "Could not move existing install directory."
    fi

    print_step "Cloning repository..."
    git clone --branch "${REPO_BRANCH}" "${REPO_URL}" "${INSTALL_DIR}" || fail "Git clone failed."
    ok "Repository cloned to ${INSTALL_DIR}"
}

setup_python_environment() {
    local py_cmd="$1"
    local venv_python="${INSTALL_DIR}/.venv/bin/python"

    print_step "Setting up Python virtual environment..."
    if [ ! -d "${INSTALL_DIR}/.venv" ]; then
        "${py_cmd}" -m venv "${INSTALL_DIR}/.venv" || fail "Failed to create virtual environment."
        ok "Virtual environment created"
    else
        ok "Virtual environment already exists"
    fi

    "${venv_python}" -m pip install --upgrade pip || fail "Failed to upgrade pip."
    "${venv_python}" -m pip install -r "${INSTALL_DIR}/requirements.txt" || fail "Failed to install requirements."
    ok "Dependencies installed"
}

setup_runtime_files() {
    print_step "Configuring runtime files..."

    if [ ! -f "${INSTALL_DIR}/config.py" ]; then
        cp "${INSTALL_DIR}/config_template.py" "${INSTALL_DIR}/config.py" || fail "Could not create config.py"
        ok "Created config.py from template"
    else
        ok "config.py already exists"
    fi

    if [ ! -f "${INSTALL_DIR}/party_tracker.json" ]; then
        printf "{}\n" > "${INSTALL_DIR}/party_tracker.json" || fail "Could not create party_tracker.json"
        ok "Created party_tracker.json"
    else
        ok "party_tracker.json already exists"
    fi

    cat > "${INSTALL_DIR}/launch_game.command" <<'EOF'
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

if [ -x ".venv/bin/python" ]; then
    exec .venv/bin/python run_web.py
else
    exec python3 run_web.py
fi
EOF
    chmod +x "${INSTALL_DIR}/launch_game.command" || fail "Could not set execute permission on launch_game.command"
    ok "Created launch_game.command"
}

create_applescript_source() {
    local escaped_path
    escaped_path="${INSTALL_DIR//\\/\\\\}"
    escaped_path="${escaped_path//\"/\\\"}"

    cat > "${APPLESCRIPT_PATH}" <<EOF
-- NeverEndingQuest launcher for macOS Terminal
-- Auto-generated by install_neverendingquest_macos.sh

set projectPath to "${escaped_path}"
set launchCommand to "cd " & quoted form of projectPath & " && if [ -x .venv/bin/python ]; then .venv/bin/python run_web.py; else python3 run_web.py; fi"

try
    do shell script "test -d " & quoted form of projectPath
on error
    display dialog "NeverEndingQuest folder not found at: " & projectPath buttons {"OK"} default button "OK" with icon stop
    return
end try

tell application "Terminal"
    activate
    do script launchCommand
end tell
EOF
}

compile_launcher_app() {
    print_step "Building launcher app..."

    create_applescript_source
    osacompile -o "${TMP_APP_PATH}" "${APPLESCRIPT_PATH}" >/dev/null || fail "Failed to compile launcher app"

    if [ -w "/Applications" ]; then
        rm -rf "${APP_PATH}" || fail "Could not replace existing app in /Applications"
        cp -R "${TMP_APP_PATH}" "${APP_PATH}" || fail "Could not install app to /Applications"
    else
        warn "Admin privileges are required to write to /Applications"
        sudo rm -rf "${APP_PATH}" || fail "Could not remove existing app from /Applications"
        sudo cp -R "${TMP_APP_PATH}" "${APP_PATH}" || fail "Could not copy launcher app to /Applications"
    fi

    ok "Launcher app installed to ${APP_PATH}"
}

apply_app_icon() {
    local icon_source
    icon_source="${INSTALL_DIR}/dm_logo.png"

    if [ ! -f "${icon_source}" ]; then
        warn "dm_logo.png not found. Keeping default app icon."
        return 0
    fi

    if ! command -v sips >/dev/null 2>&1 || ! command -v iconutil >/dev/null 2>&1; then
        warn "Icon tools missing (sips/iconutil). Keeping default app icon."
        return 0
    fi

    mkdir -p "${ICONSET_DIR}" || return 0

    sips -z 16 16 "${icon_source}" --out "${ICONSET_DIR}/icon_16x16.png" >/dev/null 2>&1 || return 0
    sips -z 32 32 "${icon_source}" --out "${ICONSET_DIR}/icon_16x16@2x.png" >/dev/null 2>&1 || return 0
    sips -z 32 32 "${icon_source}" --out "${ICONSET_DIR}/icon_32x32.png" >/dev/null 2>&1 || return 0
    sips -z 64 64 "${icon_source}" --out "${ICONSET_DIR}/icon_32x32@2x.png" >/dev/null 2>&1 || return 0
    sips -z 128 128 "${icon_source}" --out "${ICONSET_DIR}/icon_128x128.png" >/dev/null 2>&1 || return 0
    sips -z 256 256 "${icon_source}" --out "${ICONSET_DIR}/icon_128x128@2x.png" >/dev/null 2>&1 || return 0
    sips -z 256 256 "${icon_source}" --out "${ICONSET_DIR}/icon_256x256.png" >/dev/null 2>&1 || return 0
    sips -z 512 512 "${icon_source}" --out "${ICONSET_DIR}/icon_256x256@2x.png" >/dev/null 2>&1 || return 0
    sips -z 512 512 "${icon_source}" --out "${ICONSET_DIR}/icon_512x512.png" >/dev/null 2>&1 || return 0
    sips -z 1024 1024 "${icon_source}" --out "${ICONSET_DIR}/icon_512x512@2x.png" >/dev/null 2>&1 || return 0

    iconutil -c icns "${ICONSET_DIR}" -o "${ICON_ICNS_PATH}" >/dev/null 2>&1 || return 0

    if [ -w "${APP_PATH}/Contents/Resources" ]; then
        cp "${ICON_ICNS_PATH}" "${APP_PATH}/Contents/Resources/applet.icns" || return 0
        touch "${APP_PATH}" >/dev/null 2>&1 || true
    else
        sudo cp "${ICON_ICNS_PATH}" "${APP_PATH}/Contents/Resources/applet.icns" || return 0
        sudo touch "${APP_PATH}" >/dev/null 2>&1 || true
    fi

    ok "Custom icon applied"
}

prompt_start_now() {
    local response
    printf "\nStart the server now? [y/N]: "
    read -r response
    case "${response}" in
        y|Y|yes|YES)
            open "${APP_PATH}" || warn "Could not open ${APP_PATH}. Launch it manually from Applications."
            ;;
        *)
            printf "You can launch any time from: ${APP_PATH}\n"
            ;;
    esac
}

main() {
    print_header
    printf "Installing from: github.com/%s/%s\n" "${REPO_OWNER}" "${REPO_NAME}"
    printf "Install location: %s\n\n" "${INSTALL_DIR}"

    print_step "Step 1: Checking prerequisites..."
    require_command git "Install Git from https://git-scm.com/download/mac"
    require_command osacompile "macOS AppleScript compiler is required"

    local py_cmd=""
    if command -v python3 >/dev/null 2>&1 && check_python_version python3; then
        py_cmd="python3"
    elif command -v python >/dev/null 2>&1 && check_python_version python; then
        py_cmd="python"
    else
        fail "Python 3.9+ is required. Install from https://www.python.org/downloads/macos/"
    fi
    ok "Python found via ${py_cmd}"

    print_step "Step 2: Installing repository..."
    install_or_update_repo

    print_step "Step 3: Installing dependencies..."
    setup_python_environment "${py_cmd}"

    print_step "Step 4: Finalizing runtime setup..."
    setup_runtime_files

    print_step "Step 5: Installing Applications launcher..."
    compile_launcher_app
    apply_app_icon

    printf "\n========================================\n"
    printf "  Installation Complete\n"
    printf "========================================\n\n"
    printf "Game folder: %s\n" "${INSTALL_DIR}"
    printf "Launcher app: %s\n" "${APP_PATH}"
    printf "Game URL: http://localhost:8357\n\n"

    prompt_start_now
}

main "$@"
