import { test, expect } from '@playwright/test'
for (const width of [360, 390]) {
  test(`small-screen Settings stays in viewport and supports keyboard at ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/play/')
    const trigger = page.getByRole('button', { name: 'Settings', exact: true })
    await trigger.focus()
    await page.keyboard.press('Enter')
    const dropdown = page.locator('.neq-settings-dropdown-parity')
    await expect(dropdown).toBeVisible()
    const rect = await dropdown.boundingBox()
    expect(rect!.x).toBeGreaterThanOrEqual(0)
    expect(rect!.x + rect!.width).toBeLessThanOrEqual(width)
    await page.keyboard.press('Tab')
    const toggle = page.getByRole('checkbox', { name: 'AI Images' })
    await expect(toggle).toBeFocused()
    const wasChecked = await toggle.isChecked()
    await page.keyboard.press('Space')
    expect(await toggle.isChecked()).toBe(!wasChecked)
    await expect(toggle.locator('+ span')).toHaveCSS('outline-style', 'solid')
    await page.screenshot({ path: info.outputPath(`settings-toggle-${width}.png`) })
    for (let step = 0; step < 25; step++) {
      if (await page.getByLabel('Provider', { exact: true }).evaluate(element => element === document.activeElement)) break
      await page.keyboard.press('Tab')
    }
    await expect(page.getByLabel('Provider', { exact: true })).toBeFocused()
    await page.screenshot({ path: info.outputPath(`settings-${width}.png`) })
    await page.keyboard.press('Escape')
    await expect(dropdown).toBeHidden()
    await expect(trigger).toBeFocused()
  })
}
test('desktop settings sections and lifecycle surfaces are interactive Ember dialogs', async ({ page }, info) => {
  await page.setViewportSize({ width: 1586, height: 992 })
  await page.goto('/play/')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const settings = page.getByRole('dialog', { name: 'Settings', exact: true })
  await expect(settings).toBeVisible()
  await expect(settings.getByLabel('Provider', { exact: true })).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: info.outputPath('settings-providers.png') })
  await settings.getByRole('button', { name: 'Voice & images' }).click()
  await expect(settings.getByRole('checkbox', { name: 'AI Images' })).toBeAttached()
  await expect(settings.getByText('AI Images', { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('settings-voice.png') })
  await settings.getByRole('button', { name: 'Map', exact: true }).click()
  await expect(settings.getByLabel('Map style')).toBeVisible()
  await settings.getByRole('button', { name: 'Done' }).click()
  await expect(settings).toBeHidden()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Save Game' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('save.png') })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
  for (const action of ['Load', 'Reset', 'Journal']) {
    await page.getByRole('button', { name: action, exact: true }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.screenshot({ path: info.outputPath(`${action.toLowerCase()}.png`) })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
  }
})
