import { expect, test } from '@playwright/test'

test.skip(process.env.NEQ_E2E_EMBER_VISUAL !== '1', 'Scripted populated Ember preview only')

test('right-side NPC details open the complete live card and all seven original menus', async ({ page }, info) => {
  await page.setViewportSize({ width: 1586, height: 992 })
  await page.goto('/play/')
  await expect(page.locator('.neq-character-name')).toHaveText('Smashing Jack')
  await page.evaluate(() => document.fonts.ready)
  const entry = page.locator('.ember-people .ember-person-entry').filter({ has: page.locator('[data-name="Ranger Elen"]') })
  await expect(entry.locator('.ember-party-vitals')).toContainText('HP 14 / 14')
  await expect(entry.locator('.ember-party-vitals')).toContainText('AC 13')
  await expect(entry.locator('.ember-party-vitals')).toContainText('XP 0 / 300')
  const details = entry.getByRole('button', { name: 'Ranger Elen full character details' })
  await details.click()
  const card = page.getByRole('dialog', { name: 'Ranger Elen — Character', exact: true })
  await expect(card.locator('.neq-npc-name')).toHaveText('Ranger Elen')
  await expect(card).toContainText('Careful and observant.')
  await expect(card.locator('.neq-npc-abilities')).toBeVisible()
  await expect(card.locator('.ember-chip-portrait')).toHaveCSS('background-size', 'cover')
  await expect(card.locator('.ember-coin-GP')).toHaveCSS('width', '18px')
  await expect.poll(() => card.locator('.ember-chip-portrait').evaluate(node => getComputedStyle(node).backgroundImage)).not.toBe('none')
  await page.screenshot({ path: info.outputPath('npc-full-card.png') })
  for (const name of ['Saving Throw', 'Skills', 'Inventory', 'Key Abilities', 'Racial Traits', 'Background', 'Spells']) {
    const action = card.getByRole('button', { name, exact: true })
    await action.click()
    await expect(page.getByRole('dialog')).toHaveCount(2)
    await page.keyboard.press('Escape')
    await expect(card).toBeVisible()
    await expect(action).toBeFocused()
  }
  await page.keyboard.press('Escape')
  await expect(card).toHaveCount(0)
  await expect(details).toBeFocused()
  await details.blur()
  for (const name of ['Ranger Marcus', 'Scout Kira', 'Messenger Tom', 'Rusk']) {
    await page.getByRole('button', { name: `${name} full character details`, exact: true }).click()
    const otherCard = page.getByRole('dialog', { name: `${name} — Character`, exact: true })
    await expect(otherCard.locator('.neq-npc-name')).toHaveText(name)
    await expect(otherCard.getByRole('button', { name: 'Inventory', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(otherCard).toHaveCount(0)
  }
  await page.locator('.ember-people .neq-chip-scroller').evaluate(node => { node.scrollTop = 0 })
  await page.locator('.ember-people .ember-person-details').last().blur()
  await page.locator('.neq-game-log').evaluate(node => { node.scrollTop = 0 })
  await page.getByRole('textbox', { name: 'Player input' }).blur()
  await page.locator('.ember-chip-portrait').evaluateAll(nodes => Promise.all(nodes.map(async node => {
    const url = getComputedStyle(node).backgroundImage.match(/^url\(["']?(.*?)["']?\)$/)?.[1]
    if (url) { const image = new Image(); image.src = url; await image.decode() }
  })))
  await page.screenshot({ path: info.outputPath('ember-party-stats.png') })
  await page.getByRole('button', { name: 'Journal', exact: true }).click()
  const journal = page.getByRole('dialog', { name: 'Adventure Journal' })
  await expect(journal.locator('.neq-journal-page')).toHaveCount(2)
  await expect(journal.locator('.neq-journal-page').first()).toHaveCSS('background-color', 'rgb(243, 233, 210)')
  await expect(journal).toContainText('The Thornwood Road')
  await page.screenshot({ path: info.outputPath('parchment-journal.png') })
})

test('roster statistics remain readable on a small desktop and phone keeps its existing rail', async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 768 })
  await page.goto('/play/')
  await expect(page.locator('.ember-party-vitals').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Ranger Elen full character details' }).click()
  const card = page.getByRole('dialog', { name: 'Ranger Elen — Character' })
  await expect(card.getByRole('button', { name: 'Spells', exact: true })).toBeInViewport()
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.ember-party-vitals')).toHaveCount(0)
  await expect(page.locator('.ember-person-details')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
