import { expect, test } from '@playwright/test'

test.skip(process.env.NEQ_E2E_REAL_RUNTIME !== '1', 'Requires isolated real-Flask export')
test.describe.configure({ mode: 'serial' })

test('real legacy and React routes render and hydrate public data', async ({ page, request }) => {
  await request.post('/__parity__/scenario/exploration')
  const legacy = await request.get('/')
  expect(legacy.status()).toBe(200)
  expect(await legacy.text()).toContain('socket.io')
  await page.setViewportSize({ width: 1586, height: 992 })
  await page.goto('/')
  await expect(page.locator('.character-name')).toHaveText('Arden Vale')
  await expect(page.locator('#game-output')).toContainText('Mosswatch answers with a low silver bell.')
  await page.goto('/play/')
  await expect(page.locator('.ember-desktop')).toBeVisible()
  await expect(page.locator('.neq-character-name')).toHaveText('Arden Vale')
  await expect(page.getByText('Mosswatch answers with a low silver bell. The road ahead is open.')).toBeVisible()
  await expect(page.locator('.neq-character-chip')).toHaveCount(6)
  await page.getByRole('tab', { name: 'Inventory', exact: true }).click()
  await expect(page.getByText('Moonlit Compass', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Load', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('Before the briar fight')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Load', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByText('AI Provider', { exact: true })).toBeVisible()
})

test('real combat hydration and transport reconnect retain the Ember shell', async ({ page, request, context }) => {
  await request.post('/__parity__/scenario/combat')
  await page.setViewportSize({ width: 1586, height: 992 })
  await page.goto('/play/')
  await expect(page.getByLabel('Combat, round 2')).toBeVisible()
  await expect(page.locator('.ember-people [data-chip="init-enemy"]')).toHaveAccessibleName('Briar Wolf')
  await context.setOffline(true)
  await expect(page.getByText('Disconnected from the game server. Reconnecting...')).toBeVisible({ timeout: 15000 })
  await context.setOffline(false)
  await expect(page.getByLabel('Connected')).toBeVisible({ timeout: 15000 })
  await expect(page.locator('.neq-character-name')).toHaveText('Arden Vale')
  await expect(page.getByLabel('Combat, round 2')).toBeVisible()
})
