import { expect, test } from '@playwright/test'

test.skip(process.env.NEQ_E2E_REAL_RUNTIME !== '1', 'Requires disposable real-Flask fixture')
test.describe.configure({ mode: 'serial' })
test.beforeEach(async ({ page, request }) => {
  expect((await request.post('/__parity__/scenario/exploration')).ok()).toBe(true)
  await page.setViewportSize({ width: 1586, height: 992 })
  await page.goto('/play/')
  await expect(page.locator('.neq-character-name')).toHaveText('Arden Vale')
  await page.evaluate(() => document.fonts.ready)
})

test('full save mode and selected load retain their public fields', async ({ page }, info) => {
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.locator('#save-mode').selectOption('full')
  await expect(page.getByText('Archive Edition Save', { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('save-full.png') })
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Load', exact: true }).click()
  await page.locator('.neq-save-item-parity').first().click()
  await expect(page.getByRole('button', { name: 'Load Game', exact: true })).toBeEnabled()
  const selected = page.locator('.neq-save-item-parity').first()
  await expect(selected).toHaveAttribute('aria-pressed', 'true')
  await selected.hover()
  await expect(selected).toHaveCSS('border-color', 'rgb(197, 160, 109)')
  await expect(selected).toHaveCSS('background-color', 'rgb(32, 39, 31)')
  await expect(selected).toHaveCSS('filter', 'none')
  await expect(page.locator('.neq-save-item-header-parity').first()).toHaveCSS('color', 'rgb(197, 160, 109)')
  await expect(page.locator('.neq-save-item-parity').first()).toHaveCSS('font-family', /Crimson Text/)
  await expect(page.locator('.neq-save-mode-badge-parity').first()).toHaveCSS('background-color', 'rgb(73, 59, 39)')
  await page.screenshot({ path: info.outputPath('load-selected.png') })
  // Cancel only: actual file lifecycle is exercised separately, never through
  // the visual fixture whose save-list response is intentionally canned.
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Load', exact: true })).toBeFocused()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Load', exact: true }).click()
  await expect(page.locator('.neq-save-item-parity').first()).toHaveCSS('font-family', /Segoe UI/)
  await expect(page.locator('.neq-save-mode-badge-parity').first()).toHaveCSS('background-color', 'rgb(33, 150, 243)')
})

test('reset confirmation is deliberate and opening or cancelling never sends reset', async ({ page }, info) => {
  const actions: string[] = []
  page.on('websocket', socket => socket.on('framesent', frame => actions.push(String(frame.payload))))
  page.on('request', request => {
    if (request.url().includes('/socket.io/') && request.method() === 'POST') actions.push(request.postData() ?? '')
  })
  await page.reload() // Attach the observer before the new socket connects.
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  const confirm = page.getByRole('button', { name: 'Confirm Reset', exact: true })
  await expect(confirm).toBeDisabled()
  const code = (await page.getByTestId('reset-code').textContent())!.trim()
  expect(code).toMatch(/^\d{5}$/)
  await page.getByLabel('Reset confirmation code').fill(code)
  await expect(confirm).toBeEnabled()
  await page.screenshot({ path: info.outputPath('reset-ready.png') })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(actions.some(frame => frame.includes('request_location_data'))).toBe(true)
  expect(actions.some(frame => frame.includes('nuclearReset'))).toBe(false)
})

test('module failure blocks background actions; compression failure stays nonblocking', async ({ page, request }, info) => {
  await request.post('/__parity__/scenario/module-failed-progress')
  await expect(page.locator('.neq-module-progress-parity')).toBeVisible()
  await request.post('/__parity__/scenario/module-failed')
  await expect(page.getByText('Adventure forging failed safely.', { exact: true })).toBeVisible()
  expect(await page.locator('.neq-app-grid').evaluate(node => !!node.closest('[inert]'))).toBe(true)
  await page.screenshot({ path: info.outputPath('module-failure.png') })
  await request.post('/__parity__/scenario/exploration')
  await page.reload()
  await request.post('/__parity__/scenario/compression-error')
  await expect(page.getByText('The chronicle archive is temporarily unavailable.', { exact: false })).toBeVisible()
  expect(await page.locator('.neq-app-grid').evaluate(node => !!node.closest('[inert]'))).toBe(false)
  await page.screenshot({ path: info.outputPath('compression-failure.png') })
})

test('a twenty-combatant initiative list stays scrollable while input is processing', async ({ page, request }, info) => {
  await request.post('/__parity__/scenario/combat-processing-overflow')
  await page.reload()
  const combatants = page.locator('.ember-people [data-chip^="init-"]')
  await expect(combatants).toHaveCount(20)
  await combatants.last().scrollIntoViewIfNeeded()
  await expect(combatants.last()).toBeInViewport()
  await expect(page.locator('.neq-input-container')).toBeInViewport()
  await expect(page.locator('.neq-input-field')).toBeDisabled()
  await expect(page.locator('.ember-combat-caption')).toHaveCSS('color', 'rgb(197, 160, 109)')
  await expect(page.locator('.ember-round-label')).toHaveCSS('font-size', '14px')
  await expect(page.locator('.ember-round-value')).toHaveText('7')
  await expect(page.locator('.ember-round-value')).toHaveCSS('font-family', /Crimson Text/)
  await page.screenshot({ path: info.outputPath('combat-overflow.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.ember-combat-caption')).toHaveCSS('color', 'rgb(255, 165, 0)')
  await expect(page.locator('.ember-combat-caption')).toHaveCSS('font-size', '13px')
})
