import { expect, test } from '@playwright/test'

test.skip(process.env.NEQ_E2E_REAL_RUNTIME !== '1', 'Requires isolated public Flask fixture')
test.beforeEach(async ({ page, request }) => {
  await request.post('/__parity__/scenario/exploration')
  await page.setViewportSize({ width: 1586, height: 992 })
  await page.goto('/play/')
  await expect(page.locator('.neq-character-name')).toHaveText('Arden Vale')
})

test('item inspection supports hover, keyboard dismissal and complete equipment facts', async ({ page }, testInfo) => {
  await page.getByRole('tab', { name: 'Inventory', exact: true }).click()
  await expect(page.locator('.ember-currency-row')).toContainText('GP 42')
  const item = page.getByRole('button', { name: 'Longbow', exact: true })
  await item.hover()
  const details = page.getByRole('dialog', { name: 'Longbow details' })
  await expect(details).toContainText('A weathered yew longbow.')
  await expect(details).toContainText('Equipped')
  await item.click()
  await expect(details.getByRole('button', { name: 'Close Longbow details' })).toBeFocused()
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: testInfo.outputPath('inventory-inspection.png') })
  await page.keyboard.press('Escape')
  await expect(details).toHaveCount(0)
  await expect(item).toBeFocused()
  await expect(item).toHaveAttribute('aria-expanded', 'false')
})

test('spell inspection uses public metadata and stays within a short viewport', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1024, height: 768 })
  await page.getByRole('tab', { name: 'Spells & Magic', exact: true }).click()
  const spell = page.getByRole('button', { name: 'Goodberry', exact: true })
  await spell.focus()
  const details = page.getByRole('dialog', { name: 'Goodberry details' })
  await expect(details).toContainText('Range')
  await expect(details).toContainText('Duration')
  await expect(details).toContainText('Materials')
  await spell.press('Enter')
  const rect = await details.boundingBox()
  expect(rect!.x).toBeGreaterThanOrEqual(0)
  expect(rect!.y).toBeGreaterThanOrEqual(0)
  expect(rect!.x + rect!.width).toBeLessThanOrEqual(1024)
  expect(rect!.y + rect!.height).toBeLessThanOrEqual(768)
  await page.screenshot({ path: testInfo.outputPath('spell-inspection.png') })
  await page.keyboard.press('Escape')
  await expect(details).toHaveCount(0)
})

test('switching inspection or tab removes obsolete detail', async ({ page }) => {
  await page.getByRole('tab', { name: 'Inventory', exact: true }).click()
  await page.getByRole('button', { name: 'Longbow', exact: true }).hover()
  await expect(page.locator('.ember-inspection')).toHaveCount(1)
  await page.getByRole('button', { name: 'Moonlit Compass', exact: true }).hover()
  await expect(page.locator('.ember-inspection')).toHaveCount(1)
  await expect(page.locator('.ember-inspection')).toContainText('Charges')
  await page.getByRole('tab', { name: 'Character', exact: true }).click()
  await expect(page.locator('.ember-inspection')).toHaveCount(0)
})

test('hover Escape preserves external focus and passive hover cannot steal pinned focus', async ({ page }) => {
  await page.getByRole('tab', { name: 'Inventory', exact: true }).click()
  const input = page.getByRole('textbox', { name: 'Player input' })
  await input.focus()
  const bow = page.getByRole('button', { name: 'Longbow', exact: true })
  await bow.hover()
  await expect(page.locator('.ember-inspection')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await expect(page.locator('.ember-inspection')).toHaveCount(0)
  await expect(input).toBeFocused()
  await bow.click()
  const close = page.getByRole('button', { name: 'Close Longbow details' })
  await expect(close).toBeFocused()
  await page.getByRole('button', { name: 'Moonlit Compass', exact: true }).hover()
  await expect(close).toBeFocused()
  await expect(page.getByRole('dialog', { name: 'Longbow details' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Moonlit Compass', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Close Moonlit Compass details' })).toBeFocused()
  await expect(page.locator('.ember-inspection')).toHaveCount(1)
})

test('touch-enabled desktop can open and dismiss item details', async ({ browser }) => {
  const context = await browser.newContext({ hasTouch: true, viewport: { width: 1586, height: 992 } })
  try {
    const page = await context.newPage()
    await page.goto(`${process.env.PLAYWRIGHT_BASE_URL}/play/`)
    await page.getByRole('tab', { name: 'Inventory', exact: true }).tap()
    await page.getByRole('button', { name: 'Longbow', exact: true }).tap()
    await expect(page.getByRole('dialog', { name: 'Longbow details' })).toBeVisible()
    await page.getByRole('button', { name: 'Close Longbow details' }).tap()
    await expect(page.locator('.ember-inspection')).toHaveCount(0)
  } finally { await context.close() }
})
