import { expect, test } from '@playwright/test'

test.skip(process.env.NEQ_E2E_INTERMEDIATE !== '1', 'Review-only drawer prototype, never a production layout')
for (const width of [1024, 1180]) {
  test(`header menu proposal ${width}: complete local controls, focus and no game writes`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 768 })
    const requests: string[] = []
    const errors: string[] = []
    page.on('request', request => requests.push(`${request.method()} ${new URL(request.url()).pathname}`))
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/intermediate')
    await page.evaluate(() => document.fonts.ready)
    const draft = page.getByRole('textbox', { name: 'Enter your command', exact: true })
    await draft.fill('Keep this unsent draft.')
    const opener = page.getByRole('button', { name: 'Menu', exact: false })
    await expect(opener).toBeInViewport()
    await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeInViewport()
    await opener.click()
    const menu = page.getByRole('dialog', { name: 'Game menu', exact: true })
    await expect(menu.getByRole('button', { name: 'Close game menu' })).toBeFocused()
    await expect(menu.getByRole('button', { name: 'Exit', exact: true })).toBeInViewport({ ratio: 1 })
    await page.keyboard.press('Shift+Tab')
    const exit = menu.getByRole('button', { name: 'Exit', exact: true })
    await expect(exit).toBeFocused()
    expect(await exit.evaluate(node => {
      const item = node.getBoundingClientRect()
      const clip = node.closest('.drawer-scroll')!.getBoundingClientRect()
      return item.top >= clip.top && item.bottom <= clip.bottom
    })).toBe(true)
    await expect(menu.getByRole('button', { name: 'Game Running', exact: true })).toBeDisabled()
    for (const name of ['Load saved game', 'Settings', 'Developer Toolkit', 'Update available', 'Reset game', 'Exit']) {
      await expect(menu.getByRole('button', { name, exact: false })).toBeVisible()
    }
    expect(await draft.evaluate(node => { (node as HTMLElement).focus(); return document.activeElement === node })).toBe(false)
    await menu.getByRole('button', { name: 'Exit', exact: true }).focus()
    await page.keyboard.press('Tab')
    await expect(menu.getByRole('button', { name: 'Close game menu' })).toBeFocused()
    await menu.locator('.drawer-scroll').evaluate(node => { node.scrollTop = 0 })
    await page.screenshot({ path: info.outputPath(`${width}-header-menu.png`) })
    await menu.getByRole('button', { name: 'Settings', exact: true }).click()
    await expect(menu).not.toBeVisible()
    await expect(opener).toBeFocused()
    await expect(page.getByRole('status')).toContainText('Settings selected. No game action')
    await expect(draft).toHaveValue('Keep this unsent draft.')
    await opener.click()
    await page.keyboard.press('Escape')
    await expect(menu).not.toBeVisible()
    await expect(opener).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(requests.every(request => request.startsWith('GET '))).toBe(true)
    expect(requests.some(request => /\/(api|socket\.io)(\/|\?)/.test(request))).toBe(false)
    expect(errors).toEqual([])
  })
}
test('touch opens drawers and native modal inertness blocks background focus', async ({ browser }) => {
  const context = await browser.newContext({ hasTouch: true, viewport: { width: 1024, height: 768 } })
  try {
    const page = await context.newPage()
    await page.goto(`${process.env.PLAYWRIGHT_BASE_URL}/intermediate`)
    const opener = page.locator('[data-open="sheet-drawer"]')
    await opener.tap()
    const sheet = page.getByRole('dialog', { name: 'Character sheet', exact: true })
    await expect(sheet).toBeVisible()
    expect(await page.locator('#command').evaluate(node => {
      ;(node as HTMLTextAreaElement).focus()
      return document.activeElement === node
    })).toBe(false)
    await sheet.getByRole('button', { name: 'Close character sheet' }).tap()
    await expect(sheet).not.toBeVisible()
    await expect(opener).toBeFocused()
    const peopleOpener = page.locator('[data-open="people-drawer"]')
    await peopleOpener.tap()
    await expect(page.getByRole('dialog', { name: 'Party & nearby', exact: true })).toBeVisible()
    await page.touchscreen.tap(30, 350)
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(peopleOpener).toBeFocused()
  } finally { await context.close() }
})
for (const width of [1024, 1180]) {
  test(`intermediate ${width}: modal drawers, draft, scroll and sample controls`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 768 })
    const requests: string[] = []
    const errors: string[] = []
    page.on('request', request => requests.push(`${request.method()} ${new URL(request.url()).pathname}`))
    page.on('pageerror', error => errors.push(error.message))
    await page.route('**/*', route => {
      if (new URL(route.request().url()).origin !== new URL(process.env.PLAYWRIGHT_BASE_URL!).origin) return route.abort()
      return route.continue()
    })
    await page.goto('/intermediate')
    await page.evaluate(() => document.fonts.ready)
    await expect(page.locator('.study-bar')).toContainText('Not approved')
    await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(8, 13, 13)')
    expect(await page.evaluate(() => document.fonts.check('18px "Crimson Text"'))).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const draft = page.getByRole('textbox', { name: 'Enter your command', exact: true })
    await draft.fill('I compare the tracks with my notes.\nThen I ask Elen about the bridge.')
    await page.screenshot({ path: info.outputPath(`${width}-main.png`) })
    const story = page.locator('#story')
    await story.evaluate(node => { node.scrollTop = 180 })
    const storyScroll = await story.evaluate(node => node.scrollTop)
    const sheetOpener = page.locator('[data-open="sheet-drawer"]')
    await sheetOpener.click()
    const sheet = page.getByRole('dialog', { name: 'Character sheet', exact: true })
    await expect(sheet.getByRole('button', { name: 'Close character sheet' })).toBeFocused()
    await expect(sheetOpener).toHaveAttribute('aria-expanded', 'true')
    for (let index = 0; index < 8; index++) {
      await page.keyboard.press('Tab')
      expect(await sheet.evaluate(node => node.contains(document.activeElement))).toBe(true)
    }
    await page.screenshot({ path: info.outputPath(`${width}-sheet.png`) })
    const sheetScroll = page.locator('#sheet-scroll')
    await sheetScroll.evaluate(node => { node.scrollTop = 220 })
    const savedSheetScroll = await sheetScroll.evaluate(node => node.scrollTop)
    expect(savedSheetScroll).toBeGreaterThan(0)
    await page.keyboard.press('Escape')
    await expect(sheet).not.toBeVisible()
    await expect(sheetOpener).toBeFocused()
    expect(await story.evaluate(node => node.scrollTop)).toBe(storyScroll)
    await expect(draft).toHaveValue('I compare the tracks with my notes.\nThen I ask Elen about the bridge.')
    await sheetOpener.click()
    expect(await sheetScroll.evaluate(node => node.scrollTop)).toBe(savedSheetScroll)
    await sheet.getByRole('tab', { name: 'Inventory', exact: true }).click()
    await sheet.getByRole('searchbox', { name: 'Filter sample items' }).fill('potion')
    await expect(sheet.locator('[data-item]:visible')).toHaveCount(1)
    await page.keyboard.press('Escape')
    await sheetOpener.click()
    await expect(sheet.getByRole('tab', { name: 'Inventory', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(sheet.getByRole('searchbox', { name: 'Filter sample items' })).toHaveValue('potion')
    await sheet.getByRole('tab', { name: 'Inventory', exact: true }).focus()
    await page.keyboard.press('ArrowRight')
    await expect(sheet.getByRole('tab', { name: 'Spells & Magic', exact: true })).toBeFocused()
    await page.keyboard.press('Home')
    await expect(sheet.getByRole('tab', { name: 'Character', exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    const peopleOpener = page.locator('[data-open="people-drawer"]')
    await peopleOpener.click()
    const people = page.getByRole('dialog', { name: 'Party & nearby', exact: true })
    await expect(people).toBeVisible()
    await page.screenshot({ path: info.outputPath(`${width}-party.png`) })
    const peopleScroll = page.locator('#people-scroll')
    await peopleScroll.evaluate(node => { node.scrollTop = 180 })
    const savedPeopleScroll = await peopleScroll.evaluate(node => node.scrollTop)
    expect(savedPeopleScroll).toBeGreaterThan(0)
    await page.keyboard.press('Escape')
    await expect(peopleOpener).toBeFocused()
    await peopleOpener.click()
    expect(await peopleScroll.evaluate(node => node.scrollTop)).toBe(savedPeopleScroll)
    await page.setViewportSize({ width: width === 1024 ? 1180 : 1024, height: 768 })
    await expect(people).toBeVisible()
    expect((await people.boundingBox())!.width).toBe(350)
    await page.keyboard.press('Escape')
    await expect(draft).toHaveValue('I compare the tracks with my notes.\nThen I ask Elen about the bridge.')
    await page.setViewportSize({ width, height: 768 })
    await page.getByLabel('Sample view').selectOption('combat')
    await peopleOpener.click()
    const initiative = page.getByRole('dialog', { name: 'Initiative · Round 2', exact: true })
    await expect(initiative.locator('.person h3')).toHaveText(['Goblin', 'Arden Vale', 'Ranger Elen', 'Goblin scout', 'Scout Kira'])
    await page.screenshot({ path: info.outputPath(`${width}-initiative.png`) })
    await page.keyboard.press('Escape')
    await page.getByLabel('Inline image', { exact: true }).uncheck()
    await expect(page.locator('#inline-art')).toBeHidden()
    await story.evaluate(node => { node.scrollTop = 0 })
    await page.screenshot({ path: info.outputPath(`${width}-text-only.png`) })
    await peopleOpener.click()
    await page.mouse.click(30, 350)
    await expect(initiative).not.toBeVisible()
    await expect(peopleOpener).toBeFocused()
    const beforeSubmit = requests.length
    await page.getByRole('button', { name: 'Try input' }).click()
    await expect(page.getByRole('status')).toContainText('No game turn was sent')
    await expect(story).toContainText('I compare the tracks with my notes.')
    expect(requests.length).toBe(beforeSubmit)
    expect(requests.every(request => request.startsWith('GET '))).toBe(true)
    expect(requests.some(request => /\/(api|socket\.io)(\/|\?)/.test(request))).toBe(false)
    expect(errors).toEqual([])
  })
}
