import { expect, test } from '@playwright/test'

for (const width of [1440, 1280]) {
  test(`dice insertion and requested checks continue at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/play/')
    const input = page.getByRole('textbox', { name: 'Player input' })
    await expect(input).toBeEnabled()
    await input.fill('I strike. ')
    await page.getByTitle('Roll D8', { exact: true }).click()
    const insert = page.getByRole('button', { name: 'Insert roll', exact: true })
    await expect(insert).toBeEnabled()
    if (width === 1440) {
      const button = await insert.boundingBox()
      const clear = await page.getByTitle('Clear results').boundingBox()
      expect(Math.abs(button!.x + button!.width - clear!.x - clear!.width)).toBeLessThan(15)
      expect(button!.y).toBeGreaterThan(clear!.y)
    }
    await insert.click()
    await expect(input).toHaveValue(/^I strike\. I rolled a [1-8] on a d8\.$/)
    await page.getByRole('button', { name: 'Send', exact: true }).click()
    await expect(input).toBeEnabled()
    await input.fill('Inspect the gate for a check')
    await page.getByRole('button', { name: 'Send', exact: true }).click()
    const check = page.getByRole('region', { name: 'Requested check' })
    await expect(check).toBeVisible()
    // On the desktop layout the check's submit controls sit beside the quick
    // dice and Clear, so the dice just rolled are submitted from where they are.
    const submitControls = page.locator('.neq-dice-submit-controls')
    await page.getByTitle('Roll D20', { exact: true }).click()
    await submitControls.getByRole('button', { name: /Submit rolled dice/ }).click()
    await expect(page.getByText(/Your submitted dice .* reveal the concealed door/)).toBeVisible()
    await expect(input).toBeEnabled()
    await input.fill('Inspect the gate for a check')
    await page.getByRole('button', { name: 'Send', exact: true }).click()
    await submitControls.getByRole('button', { name: 'Roll for me', exact: true }).click()
    await expect(page.getByText('The engine rolled for you. You spot the concealed door.')).toBeVisible()
    await expect(input).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`public-dice-${width}.png`) })
  })
}

test('desktop player alignment, dragon and full scene preview', async ({ page }, info) => {
  test.skip(process.env.NEQ_E2E_EMBER_VISUAL !== '1', 'Scene fixture requires visual assets')
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/play/')
  const player = page.locator('.neq-message-user').first()
  await expect(player).toBeVisible()
  await expect(player.locator('.neq-message-text')).toHaveCSS('text-align', 'right')
  await expect(page.locator('.neq-message-narration .neq-message-avatar img').first()).toHaveAttribute('src', /dm-bronze-dragon/)
  await page.getByRole('button', { name: /Open scene preview/ }).first().click()
  const preview = page.getByRole('dialog', { name: 'Scene preview' })
  await expect(preview).toBeVisible()
  await preview.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(preview.getByLabel('Zoom level')).toHaveText('150%')
  await page.screenshot({ path: info.outputPath('public-scene-preview.png') })
  await page.keyboard.press('Escape')
  await expect(preview).toBeHidden()
  await expect(page.getByLabel('Player input')).toBeEnabled()
})
