"""
Validator modules for API callsite validation.
Auto-generated by tools/discover_validators.py
"""

# Auto-generated imports
from validators import task_T035
from validators import task_T051
from validators import task_T054
from validators import task_T065
from validators import task_T067
from validators import task_T077
from validators import task_T078
from validators import task_T079
from validators import task_T082
from validators import task_T090

__all__ = [
    "task_T035",
    "task_T051",
    "task_T054",
    "task_T065",
    "task_T067",
    "task_T077",
    "task_T078",
    "task_T079",
    "task_T082",
    "task_T090"
]
